import React from "react";
import * as Icons from "lucide-react";

export const ICON_NAMES = [
  "Activity",
  "AlertCircle",
  "AlertTriangle",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "Avatar",
  "BarChart",
  "BarChart2",
  "Bell",
  "Book",
  "Bookmark",
  "Box",
  "Calendar",
  "Check",
  "CheckCircle",
  "CheckCircle2",
  "CheckSquare",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "Clock",
  "CreditCard",
  "Database",
  "DollarSign",
  "Download",
  "Edit",
  "Edit3",
  "Eye",
  "File",
  "FileText",
  "Filter",
  "Folder",
  "FolderOpen",
  "Globe",
  "Heart",
  "Home",
  "Image",
  "Inbox",
  "Info",
  "Layers",
  "Layout",
  "Link",
  "List",
  "Lock",
  "LogOut",
  "Mail",
  "MapPin",
  "Menu",
  "MessageSquare",
  "Minus",
  "MoreHorizontal",
  "MoreVertical",
  "Package",
  "Percent",
  "Phone",
  "PieChart",
  "Play",
  "Plus",
  "Power",
  "RefreshCw",
  "Search",
  "Send",
  "Settings",
  "Share2",
  "Shield",
  "ShoppingBag",
  "ShoppingCart",
  "Sliders",
  "Smartphone",
  "Sparkles",
  "Star",
  "Table",
  "Tablet",
  "Tag",
  "Trash",
  "Trash2",
  "TrendingDown",
  "TrendingUp",
  "Truck",
  "Unlock",
  "Upload",
  "User",
  "UserCheck",
  "UserPlus",
  "Users",
  "Video",
  "Wallet",
  "X",
  "Zap",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const DynamicIcon: React.FC<{
  name: string;
  className?: string;
  size?: number;
  color?: string;
}> = ({ name, className = "w-4 h-4", size, color }) => {
  const IconComponent = (Icons as Record<string, any>)[name] || Icons.HelpCircle;
  return <IconComponent className={className} size={size} color={color} />;
};
